export const immersion=`<div class="immersion-controls"><button id="motion-toggle" type="button" aria-pressed="false" hidden>Réduire les animations</button><a class="entry-scroll" href="#approche" aria-label="Découvrir la suite"><svg width="22" height="36" viewBox="0 0 22 36" fill="none" aria-hidden="true"><path d="M11 2v30M3 24l8 8 8-8" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg></a></div>
<section class="depth-journey" aria-label="Découvrir l’approche d’Arnaud Crestey en cinq étapes"><div class="depth-stage"><canvas id="depth-dust" aria-hidden="true"></canvas><div class="depth-light" aria-hidden="true"></div><div class="depth-axis" aria-hidden="true"></div>
<section class="depth-scene depth-intro" data-scene="0" aria-labelledby="scene-title-0">
<div class="entry-brand">
<p class="entry-signature">Comprendre avant d’agir</p>
<svg class="entry-logo" viewBox="281 482 1459 1019" role="img" aria-label="AC — arnaudcrestey.com"><image href="/assets/signature-ac.png" width="2000" height="2000"/></svg>
<h1 id="scene-title-0">Communication <span>&amp; stratégie digitale</span></h1>
<p class="entry-purpose"><span>J’aide les petites entreprises à clarifier leur communication et</span> <span>à créer un site vivant : un site qui présente leur activité,</span> <span>évolue avec leurs offres et invite leurs clients</span> <span>à participer ou à les contacter.</span></p>
</div>
</section>
<aside class="day-interlude" aria-label="Une respiration au fil du jour">
<div class="day-note"><time class="day-date"><span class="day-weekday">Aujourd’hui</span><span class="day-number"></span><span class="day-month"></span></time><span class="day-rule" aria-hidden="true"></span><p class="day-message">Aujourd’hui, qu’aimeriez-vous<br><em>faire avancer ?</em></p></div>
</aside>
<section class="depth-scene offer-scene offer-clarify" data-scene="1" id="approche" aria-labelledby="scene-title-1">
<div class="offer-copy"><p class="offer-step">01 / AVANT DE CRÉER</p><h2 id="scene-title-1">Faire le point<br><em>avant d’agir.</em></h2><p>Un échange pour comprendre votre activité, ce que vous proposez et les clients à qui vous vous adressez.</p><p class="offer-outcome">Vous repartez avec un besoin clarifié, des priorités et une première direction.</p></div>
<div class="clarity-sheet offer-aside"><p class="aside-label">CE QUE NOUS CLARIFIONS ENSEMBLE</p><ol class="offer-lines"><li><span>01</span><div><h3>Votre activité</h3><p>Ce que vous faites, pour qui et avec quelle différence.</p></div></li><li><span>02</span><div><h3>Votre message</h3><p>Ce que vos futurs clients doivent comprendre.</p></div></li><li><span>03</span><div><h3>Votre priorité</h3><p>Ce dont votre activité a le plus besoin aujourd’hui.</p></div></li></ol></div>
</section>
<section class="depth-scene offer-scene offer-entry" data-scene="2" id="exemples" aria-labelledby="scene-title-2">
<div class="offer-copy"><p class="offer-step">02 / UN PREMIER OUTIL CONCRET</p><h2 id="scene-title-2">Le point<br><em>d’entrée.</em></h2><p>Une question, un quiz ou un mini-diagnostic qui invite vos futurs clients à participer plutôt qu’à seulement regarder.</p><p class="offer-outcome">Un outil sur mesure, partageable par lien ou QR code, pour ouvrir un premier échange.</p></div>
<figure class="offer-example offer-aside"><img src="/assets/brioche.jpg" width="1440" height="1080" alt="Brioche de Maison Jeannette, exemple fictif"><figcaption><p class="aside-label">UNE BOULANGERIE · EXEMPLE FICTIF</p><h3>Et si vos clients choisissaient<br>la brioche du mois ?</h3><p>Un vote sur le site. Une invitation à découvrir le parfum choisi en boutique.</p></figcaption></figure>
</section>
<section class="depth-scene offer-scene offer-showcase" data-scene="3" id="site-vitrine" aria-labelledby="scene-title-3">
<div class="offer-copy"><p class="offer-step">03 / PRÉSENTER VOTRE ACTIVITÉ</p><h2 id="scene-title-3">Votre site<br><em>vitrine.</em></h2><p>Un site à l’image de votre activité, pour présenter vos prestations, donner confiance et permettre à vos clients de vous contacter.</p><p class="offer-outcome">Votre savoir-faire, vos informations utiles et un contact simple. Sur ordinateur, tablette et téléphone.</p></div>
<figure class="showcase-preview offer-aside" aria-label="Exemple fictif de site vitrine pour un garage automobile, sans point d’entrée interactif">
<figcaption class="aside-label">UN GARAGE AUTOMOBILE · EXEMPLE FICTIF</figcaption>
<div class="garage-site">
<div class="garage-brand"><span>Garage des Tilleuls</span><span>GARAGE INDÉPENDANT</span></div>
<div class="garage-tabs" role="tablist" aria-label="Explorer le garage fictif" hidden><button type="button" role="tab" id="garage-tab-home" aria-controls="garage-panel-home" aria-selected="true" data-garage-tab="home">Accueil</button><button type="button" role="tab" id="garage-tab-services" aria-controls="garage-panel-services" aria-selected="false" tabindex="-1" data-garage-tab="services">Prestations</button><button type="button" role="tab" id="garage-tab-contact" aria-controls="garage-panel-contact" aria-selected="false" tabindex="-1" data-garage-tab="contact">Contact</button></div>
<div class="garage-panels">
<div class="garage-panel" id="garage-panel-home" role="tabpanel" aria-labelledby="garage-tab-home" tabindex="0">
<div class="garage-hero"><img src="/assets/garage-tilleuls.jpg" alt="Mécanicien au travail dans un garage lumineux, illustration fictive" width="1536" height="1024"><h3>Un garage de confiance,<br><em>près de chez vous.</em></h3></div>
<div class="garage-details"><p class="garage-services">Entretien · Réparation · Diagnostic</p><p class="garage-description">Un atelier de proximité pour prendre soin de votre voiture.</p><div class="garage-contact"><button type="button" class="garage-action" data-garage-open="contact">Prendre rendez-vous</button><button type="button" class="garage-practical" data-garage-open="contact">Horaires &amp; accès</button></div></div>
</div>
<div class="garage-panel garage-info" id="garage-panel-services" role="tabpanel" aria-labelledby="garage-tab-services" tabindex="0" hidden><p class="garage-section-label">NOS PRESTATIONS</p><h3>Prendre soin<br><em>de votre voiture.</em></h3><dl class="garage-service-list"><div><dt>Entretien</dt><dd>Vidange, filtres et révision périodique.</dd></div><div><dt>Réparation</dt><dd>Freinage, pneus et pièces d’usure.</dd></div><div><dt>Diagnostic</dt><dd>Identifier un voyant ou un bruit inhabituel.</dd></div></dl><button type="button" class="garage-action" data-garage-open="contact">Contacter le garage</button></div>
<div class="garage-panel garage-info" id="garage-panel-contact" role="tabpanel" aria-labelledby="garage-tab-contact" tabindex="0" hidden><p class="garage-section-label">HORAIRES ET CONTACT</p><h3>Un échange,<br><em>avant votre visite.</em></h3><dl class="garage-contact-list"><div><dt>Horaires</dt><dd>Lundi au vendredi<br>8 h 30 – 12 h / 14 h – 18 h</dd></div><div><dt>Nous trouver</dt><dd>12, rue de l’Atelier<br>Ville d’exemple</dd></div><div><dt>Téléphone</dt><dd>02 XX XX XX XX</dd></div><div><dt>E-mail</dt><dd>bonjour@garage.example</dd></div></dl><p class="garage-demo-note">Coordonnées fictives. Aucun message ni rendez-vous n’est envoyé.</p></div>
</div>
</div>
</figure>
</section>
<section class="depth-scene offer-scene offer-system" data-scene="4" id="systeme-complet" aria-labelledby="scene-title-4">
<div class="offer-copy"><p class="offer-step">04 / RÉUNIR LE TOUT</p><h2 id="scene-title-4">Le système<br><em>complet.</em></h2><p>Votre site, son contenu et son point d’entrée réunis dans un même parcours : découvrir votre activité, participer et vous contacter.</p><p class="offer-outcome">De la première réflexion à la mise en ligne, je construis avec vous un site adapté à votre activité.</p></div>
<figure class="system-preview offer-aside" aria-label="Exemple fictif de paysagiste : un point d’entrée associé à son site complet">
<figcaption class="aside-label">UN PAYSAGISTE · EXEMPLE FICTIF</figcaption>
<div class="system-composition">
<div class="landscape-site">
<div class="landscape-brand"><span>Atelier des Jardins</span><span class="preview-type">LE SITE</span></div>
<div class="landscape-hero"><img src="/assets/lisieres.jpg" alt="Jardin arboré et terrasse en pierre, illustration du site de paysagiste" width="1200" height="750"><h3>Un jardin<br><em>à votre rythme.</em></h3></div>
<div class="landscape-services"><span>Création de jardins</span><span>Terrasses & plantations</span></div>
<p class="landscape-contact">Parlons de votre jardin <span aria-hidden="true">↗</span></p>
</div>
<div class="landscape-entry"><p class="preview-type">LE POINT D’ENTRÉE</p><h3>Qu’aimeriez-vous changer<br>dans votre jardin ?</h3><ul><li>Une terrasse <span aria-hidden="true">↗</span></li><li>Plus de verdure <span aria-hidden="true">↗</span></li><li>Moins d’entretien <span aria-hidden="true">↗</span></li></ul></div>
</div>
</figure>
</section>
<section class="depth-scene offer-scene offer-followup" data-scene="5" id="faire-vivre" aria-labelledby="scene-title-5">
<div class="offer-copy"><p class="offer-step">05 / APRÈS LA MISE EN LIGNE</p><h2 id="scene-title-5">Faire vivre<br><em>votre site.</em></h2><p>Un site vivant, c’est un site qui donne régulièrement une nouvelle raison de venir vous voir.</p><p class="living-example">Une nouveauté à découvrir, une offre de saison, un événement à partager… Votre site raconte ce qui se passe chez vous et invite vos clients à en faire partie.</p></div>
<div class="living-stories offer-aside story-carousel" role="region" aria-roledescription="carrousel" aria-label="Six idées de site vivant"><p class="aside-label">DES IDÉES INSPIRÉES DE NOS UNIVERS<small class="fiction-note">Exemples fictifs</small></p><div class="story-track" id="living-stories-track" tabindex="0" aria-label="Parcourir les idées avec les flèches haut et bas">${[
['brioche.jpg','MAISON JEANNETTE · BOULANGERIE','La prochaine brioche ? À vous de choisir.','Les clients votent pour leur parfum préféré, puis découvrent la brioche choisie en boutique.'],
['clara.webp','CLARA MOREL · SOPHROLOGIE','Un atelier pour prendre une pause.','Le site présente le prochain atelier et invite à contacter la sophrologue pour y participer.'],
['cote-flamme.png','CÔTE & FLAMME · RESTAURATION','Une nouvelle saison à votre table.','Une carte de saison, un produit local à raconter : le site donne une nouvelle raison de réserver.'],
['atelier-velo.jpg','RÉPARATION DE VÉLOS','Les beaux jours reviennent. Votre vélo est prêt ?','Une semaine de révision annoncée sur le site, quelques points à vérifier et une invitation à réserver un passage à l’atelier.'],
['logement-lumineux.jpg','AGENCE IMMOBILIÈRE','Ce samedi, poussez la porte de votre futur chez-vous.','Une journée de visites : le site présente les logements à découvrir et invite à demander un créneau auprès de l’agence.'],
['fleuriste-bouquet-reference.png','FLEURISTE','Pour la fête des Mères, dites-le avec des fleurs.','Le site présente les bouquets créés pour l’occasion et invite à réserver le sien pour un retrait en boutique.']
].map(([image,name,title,description],i)=>`<figure class="living-story" role="group" aria-roledescription="diapositive" aria-label="${i+1} sur 6 : ${name}"><img src="/assets/${image}" alt="Univers ${name}" width="1200" height="800"><figcaption><p class="story-category">${name}</p><h3><a class="story-link" href="/exemples/${['#tab-bakery','#tab-clara','#tab-flamme'][i]||''}" aria-label="Voir les exemples — ${name}">${title}</a></h3><p>${description}</p></figcaption></figure>`).join('')}</div><div class="story-controls"><span class="story-count" aria-live="polite" aria-atomic="true">01 / 06</span><div><button type="button" data-story-prev aria-label="Idée précédente" aria-controls="living-stories-track" disabled>↑</button><button type="button" data-story-next aria-label="Idée suivante" aria-controls="living-stories-track">↓</button></div></div></div>
</section>
</div></section><nav class="depth-navigation" aria-label="Étapes de la découverte">${['Accueil','Faire le point','Point d’entrée','Site vitrine','Système complet','Suivi & évolutions'].map((x,i)=>`<button data-depth-go="${i}" aria-label="${i===0?'Accueil':`Étape ${i} : ${x}`}" ${i===0?'aria-current="step"':''}>${i===0?'':`<span>0${i}</span>`}<b>${x}</b></button>`).join('')}</nav>
<section class="after-journey" id="arnaud" aria-labelledby="arnaud-title"><figure><img src="/assets/arnaud-crestey.jpg" alt="Arnaud Crestey" width="1179" height="1747"><figcaption>ARNAUD CRESTEY</figcaption></figure><div><p class="offer-step">À propos</p><h2 id="arnaud-title">Les outils, après.<br><em>Vous, d’abord.</em></h2><p>Ce qui m’anime, ce sont les projets. Une idée qui prend forme, quelque chose à apprendre, une nouvelle possibilité à explorer.</p><p>Pendant 25 ans, en tant que cadre dirigeant dans le secteur social, j’ai contribué à faire évoluer une association à travers de nombreux projets. Parmi eux, le service <a class="about-project-link" href="https://www.osys14.com/" target="_blank" rel="noopener noreferrer" aria-label="OSYS, ouvrir le site dans un nouvel onglet">OSYS</a>, dédié aux victimes de violences conjugales, dont j’ai également créé le site. De ce parcours, je garde une conviction : comprendre les personnes et leurs besoins avant d’agir.</p><p>Ma curiosité pour les nouvelles technologies m’a conduit à me former, à expérimenter et à créer mes propres sites. Au fil des projets, j’ai appris à transformer mes idées en réalisations concrètes, avec le même plaisir d’apprendre et de construire.</p><p>Aujourd’hui, je mets cette curiosité et cette expérience au service de votre activité : clarifier vos besoins, créer un site qui vous ressemble et le faire évoluer avec vos projets.</p><div class="after-actions"><a href="/contact/" class="after-card after-card-contact"><span class="after-card-kicker">Échanger</span><span class="after-card-title">Parlons de <br>votre activité</span><span class="after-card-line" aria-hidden="true"></span></a><a href="/votre-idee/" class="after-card after-card-idea"><span class="after-card-kicker">Explorer</span><span class="after-card-title">Une idée pour <br>votre entreprise</span><span class="after-card-line" aria-hidden="true"></span></a></div></div></section>`;
