const email = '<a href="mailto:demande@arnaudcrestey.com">demande@arnaudcrestey.com</a>';
const identity = '<p><strong>Arnaud Crestey — Entrepreneur individuel (EI)</strong><br>36 Route du Coisel, Viessoix / La Personnerie<br>14410 Valdallière, France<br>SIREN : 481 437 515 — RCS Caen<br>SIRET : 481 437 515 00028<br>Téléphone : <a href="tel:+33681952345">+33 6 81 95 23 45</a><br>E-mail : '+email+'</p>';
function page(title, eyebrow, intro, content) {
 return {title:title+' — Arnaud Crestey',description:intro,content:`<section class="page-intro section legal-intro"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${intro}</p></section><article class="section legal-content">${content}<p class="legal-date">Dernière mise à jour : 13 septembre 2026.</p><a class="under-link" href="/">Revenir à l’accueil</a></article>`};
}
export const legalPages = {
 'mentions-legales':page('Mentions légales','INFORMATIONS LÉGALES','Les informations relatives à l’éditeur et à l’utilisation du site arnaudcrestey.com.',`
 <h2>Éditeur du site</h2>${identity}
 <p>Directeur de la publication : Arnaud Crestey.</p>
 <p>Activité : conseil en communication et stratégie digitale, conception de sites, de contenus et de parcours numériques pour les entreprises.</p>
 <h2>Hébergement</h2><p>Le site est hébergé par <strong>Vercel Inc.</strong><br>440 N Barranca Avenue #4133<br>Covina, CA 91723, États-Unis.<br>Téléphone publié par Vercel pour son contact juridique DMCA : <a href="tel:+15592887060">+1 559 288 7060</a> (<a href="https://vercel.com/legal/dmca-policy">source officielle</a>).<br>Assistance technique : <a href="https://vercel.com/help">assistance Vercel</a>.<br>Protection des données : <a href="https://vercel.com/legal/privacy-notice">politique de Vercel</a>.</p>
 <h2>Propriété intellectuelle</h2><p>Les textes, logos, images et réalisations présentés appartiennent à leurs titulaires respectifs. Leur utilisation est soumise aux autorisations et licences applicables, ainsi qu’aux exceptions prévues par la loi. Les composants tiers conservent leurs propres licences.</p><p>Les exemples signalés comme fictifs sont des démonstrations, pas des témoignages de clients. Ils ne déclenchent aucune commande, réservation ou participation réelle.</p>
 <h2>Utilisation et responsabilité</h2><p>Le site présente les services d’Arnaud Crestey et permet de prendre contact. L’atelier fournit des pistes générées par IA, à apprécier selon votre situation : elles peuvent comporter des erreurs et ne garantissent aucun résultat commercial. Aucun achat n’est conclu par l’utilisation de l’atelier ou l’envoi du formulaire de contact.</p><p>Si vous constatez une erreur, signalez-la à ${email}. Les liens externes conduisent à des services gérés par leurs propres éditeurs. Les présentes informations ne limitent pas les responsabilités qui ne peuvent être exclues par la loi.</p>
 <h2>Données personnelles et cookies</h2><p>Consultez la <a href="/confidentialite/">politique de confidentialité</a> et la <a href="/cookies/">politique de cookies</a> pour connaître les données traitées, les prestataires et vos droits.</p>
 <h2>Prestations</h2><p>Les <a href="/tarifs/">tarifs</a> présentent les offres. Le périmètre d’une prestation, ses modalités de règlement et les conditions applicables sont à convenir par écrit avant tout engagement. Les informations fiscales applicables à la prestation sont précisées sur le devis et la facture.</p>
 <h2>Droit applicable</h2><p>Le site relève du droit français, sous réserve des dispositions impératives applicables.</p>`),
 'confidentialite':page('Politique de confidentialité','PROTECTION DES DONNÉES','Les données utilisées pour répondre à vos demandes, faire fonctionner l’atelier et protéger le site.',`
 <h2>1. Responsable du traitement</h2>${identity}
 <h2>2. Contact</h2><p>Le formulaire demande un prénom ou un nom d’entreprise, un e-mail ou un téléphone, un sujet et un message. Les champs obligatoires permettent de traiter la demande et de vous répondre ; sans eux, le formulaire ne peut pas être envoyé. Il n’est pas nécessaire de fournir à la fois un e-mail et un téléphone.</p><p>À votre demande, le serveur hébergé sur Vercel transmet ces informations à demande@arnaudcrestey.com par Hostinger Email. Si vous avez renseigné un e-mail, un accusé de réception lui est envoyé. Les coordonnées de contact ne sont pas transmises à OpenAI. Les messages sont accessibles aux personnes habilitées à traiter votre demande.</p>
 <h2>3. Atelier personnalisé</h2><p>L’atelier utilise le secteur, la description de l’activité, l’objectif et la présence en ligne que vous renseignez. Lors de la génération, ces réponses sont transmises par le serveur Vercel à l’API OpenAI. Une demande de variante inclut aussi la question précédemment proposée. Aucun nom, compte ou e-mail n’est requis. Évitez de saisir des données sensibles ou confidentielles sur vous-même ou des tiers.</p><p>L’application n’enregistre pas les textes de l’atelier ni les idées générées dans une base de données. Ils restent dans la page jusqu’à son rechargement. Les choix dans les démonstrations métiers restent dans le navigateur ; ce ne sont pas des votes ou réservations réels. Aucune décision ayant un effet juridique sur vous n’est prise automatiquement par l’atelier.</p>
 <h2>4. Finalités et bases légales</h2><p>Le traitement d’une demande concernant une prestation repose sur les mesures précontractuelles prises à votre initiative. Les demandes générales et la mise à disposition de l’atelier facultatif relèvent de l’intérêt légitime de l’entreprise à répondre à ses interlocuteurs et à présenter des pistes adaptées à leur activité. La prévention des abus, des envois répétés et des usages excessifs relève de son intérêt légitime à sécuriser le service. Vous pouvez vous opposer aux traitements fondés sur l’intérêt légitime dans les conditions prévues par la réglementation.</p><p>Les données ne sont ni vendues ni louées. Elles ne servent pas à établir un profil publicitaire ou à vous inscrire automatiquement à une prospection commerciale.</p>
 <h2>5. Hébergement et prestataires</h2><p><strong>Vercel</strong> héberge le site, exécute les fonctions serveur et conserve les compteurs de sécurité dans un stockage privé. Il traite également les informations techniques nécessaires à l’acheminement et à la protection des requêtes, notamment l’adresse IP. <strong>Hostinger Email</strong> assure l’envoi et l’hébergement des messages. <strong>OpenAI</strong> traite les réponses de l’atelier pour générer les idées.</p><p>Certains traitements peuvent avoir lieu hors de l’Espace économique européen, notamment aux États-Unis. Les documents des prestataires décrivent les garanties et mécanismes contractuels qu’ils proposent, dont les clauses contractuelles types selon les cas : <a href="https://vercel.com/legal/dpa">Vercel</a>, <a href="https://www.hostinger.com/legal/dpa">Hostinger</a> et <a href="https://openai.com/policies/data-processing-addendum/">OpenAI</a>. Pour obtenir des précisions sur les garanties applicables à votre demande, écrivez à ${email}.</p>
 <h2>6. Conservation</h2><p><strong>Atelier :</strong> aucun archivage applicatif des textes ou des résultats n’est effectué par ce site. L’option de stockage des réponses OpenAI pour récupération ultérieure est désactivée. Cela ne supprime pas les éventuels journaux de prévention des abus du prestataire : ils peuvent contenir des données pendant jusqu’à 30 jours, sauf exceptions ou obligations prévues par sa politique. Les données API ne servent pas à entraîner les modèles par défaut. Voir la <a href="https://developers.openai.com/api/docs/guides/your-data">documentation OpenAI</a>.</p><p><strong>Sécurité :</strong> des empreintes pseudonymisées de l’adresse IP, des coordonnées et du contenu d’une demande, ainsi que des identifiants d’envoi, dates, états et compteurs, servent à limiter les abus et les doublons. Ce stockage privé ne contient ni texte de message, ni e-mail, ni IP en clair. Les entrées individuelles utilisent une fenêtre de 24 heures et sont purgées lors du prochain traitement après expiration ; la purge n’est pas instantanée en l’absence de nouvelle activité. Les compteurs globaux de lancement sont conservés tant que ces limites sont actives. Les journaux techniques propres aux prestataires suivent leurs règles de conservation.</p><p><strong>Messages :</strong> les e-mails reçus et envoyés restent dans la messagerie professionnelle ; le formulaire n’en crée pas de base d’archivage distincte. Leur conservation dépend du traitement de la demande, de la poursuite des échanges et, lorsqu’une prestation est conclue, des obligations liées à la relation contractuelle et à la preuve. Aucune suppression automatique des e-mails n’est actuellement configurée. Vous pouvez demander l’effacement d’un échange à ${email}, sous réserve des obligations de conservation applicables.</p>
 <h2>7. Sécurité</h2><p>Les connexions au site sont chiffrées. La clé de l’atelier et le mot de passe de messagerie restent côté serveur. Des limites de taille, de fréquence et de volume protègent les formulaires ; des contrôles préviennent les envois en double. Le code applicatif ne journalise pas le texte des demandes. Aucune transmission ni aucun stockage numérique ne peut être garanti sans risque.</p>
 <h2>8. Vos droits</h2><p>Selon les conditions légales, vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition et la portabilité de vos données. Pour exercer vos droits, écrivez à ${email}. Vous pouvez aussi adresser une réclamation à la <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p>
 <h2>9. Cookies et services externes</h2><p>Le code du site n’utilise pas de cookie de mesure d’audience, de traceur publicitaire ou de stockage persistant dans le navigateur. Les préférences d’affichage ne persistent pas au rechargement. Consultez la <a href="/cookies/">politique de cookies</a>. Les services externes que vous ouvrez volontairement appliquent leurs propres politiques.</p>
 <h2>10. Évolution</h2><p>Cette politique décrit le site en ligne. Elle est mise à jour lorsque les fonctions ou les traitements évoluent.</p>`),
 'cookies':page('Politique de cookies','COOKIES ET TRACEURS','Le fonctionnement du site et vos choix en matière de cookies.',`
 <h2>1. Qu’est-ce qu’un cookie ?</h2><p>Un cookie permet à un service de mémoriser des informations dans votre navigateur. D’autres technologies peuvent remplir des fonctions similaires.</p>
 <h2>2. Fonctionnement actuel</h2><p>Le code du site ne dépose pas de cookie et n’utilise ni stockage local persistant, ni mesure d’audience, ni traceur publicitaire. Les images et les polices sont servies avec le site. Les démonstrations et les préférences d’affichage restent dans la mémoire temporaire de la page.</p><p>L’atelier communique avec OpenAI par le serveur Vercel. Le formulaire utilise Hostinger Email pour transmettre votre message. Ces fonctions ne nécessitent pas de cookie applicatif ; leur traitement de données est expliqué dans la <a href="/confidentialite/">politique de confidentialité</a>.</p>
 <h2>3. Choix et consentement</h2><p>Aucun bandeau de consentement n’est affiché pour les fonctions actuelles, qui n’intègrent pas de traceur soumis au consentement. Si de tels traceurs sont ajoutés, ils ne seront pas activés avant votre accord et un moyen de refuser ou de retirer cet accord sera proposé.</p>
 <h2>4. Préférences et durée</h2><p>Les saisies et les réglages temporaires disparaissent au rechargement. Aucun cookie applicatif persistant n’est à supprimer. Votre navigateur permet de gérer les cookies des services externes que vous consultez.</p>
 <h2>5. Hébergement et évolution</h2><p>Le site est hébergé sur Vercel, sans outil de mesure d’audience ajouté par l’éditeur. Les données techniques de sécurité traitées par l’hébergeur sont distinctes des cookies applicatifs. Cette politique sera adaptée si la configuration change.</p><p>Pour toute question : ${email}.</p>`)
};
