const email = '<a href="mailto:demande@arnaudcrestey.com">demande@arnaudcrestey.com</a>';
const identity = '<p><strong>Arnaud Crestey — Entrepreneur individuel (EI)</strong><br>36 Route du Coisel, Viessoix / La Personnerie<br>14410 Valdallière, France<br>SIREN : 481 437 515 — RCS Caen<br>SIRET : 481 437 515 00028<br>Téléphone : <a href="tel:+33681952345">+33 6 81 95 23 45</a><br>E-mail : '+email+'</p>';
function page(title, eyebrow, intro, content) {
 return {title:title+' — Arnaud Crestey',description:intro,content:`<section class="page-intro section legal-intro"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${intro}</p></section><article class="section legal-content">${content}<p class="legal-date">Dernière mise à jour : 13 septembre 2026.</p><a class="under-link" href="/">Revenir à l’accueil</a></article>`};
}
export const legalPages = {
 'mentions-legales':page('Mentions légales','INFORMATIONS LÉGALES','Les informations relatives à l’éditeur et à l’utilisation du site arnaudcrestey.com.',`
 <h2>Éditeur du site</h2>${identity}
 <p>Directeur de la publication : Arnaud Crestey.</p>
 <p>Activité : conseil en communication et stratégie digitale, accompagnement des entreprises dans la conception et l’évolution de leurs outils, contenus et dispositifs numériques.</p>
 <h2>Hébergement</h2><p><strong>Hébergeur retenu pour la mise en ligne : Vercel Inc.</strong><br>440 N Barranca Avenue #4133<br>Covina, CA 91723, États-Unis<br>Site : <a href="https://vercel.com">vercel.com</a><br>Contact : <a href="https://vercel.com/help">assistance Vercel</a><br>Protection des données : <a href="https://vercel.com/legal/privacy-notice">informations officielles de Vercel</a>.</p><p>Le nouveau site est encore en prévisualisation locale. Son hébergement sur Vercel sera activé lors de la mise en ligne validée par Arnaud Crestey ; le hub actuel n’est pas remplacé à ce stade.</p>
 <h2>Propriété intellectuelle</h2><p>Les textes, logos, éléments graphiques, images, vidéos, code et contenus éditoriaux sont protégés par les droits de propriété intellectuelle de leurs titulaires respectifs. Les contenus de tiers demeurent la propriété de leurs auteurs et sont soumis à leurs licences.</p><p>Sauf autorisation du titulaire des droits ou exception prévue par la loi, leur reproduction, modification ou exploitation n’est pas autorisée. Les exemples signalés comme fictifs sont des démonstrations et ne constituent pas des témoignages de clients.</p>
 <h2>Responsabilité</h2><p>L’éditeur s’efforce de présenter des informations exactes et à jour. Si vous constatez une erreur, vous pouvez la signaler à ${email}. Les exemples sont présentés à titre illustratif et ne garantissent pas un résultat commercial.</p><p>Les liens externes conduisent à des sites gérés par leurs propres éditeurs. Les présentes informations ne limitent pas les responsabilités qui ne peuvent être exclues par la loi.</p>
 <h2>Données personnelles</h2><p>Le fonctionnement des formulaires, l’utilisation des messages et vos droits sont décrits dans la <a href="/confidentialite/">politique de confidentialité</a>. Les données ne sont ni vendues ni louées à des tiers à des fins commerciales.</p>
 <h2>Cookies</h2><p>La version actuelle n’intègre aucun cookie, outil de mesure d’audience ou traceur publicitaire. Consultez la <a href="/cookies/">politique de cookies</a> pour connaître le fonctionnement actuel et les conditions d’une éventuelle évolution.</p>
 <h2>Conditions d’utilisation du site</h2><p>Le site présente les activités, services et dispositifs proposés par Arnaud Crestey. L’utilisateur s’engage à en faire un usage loyal, conforme à sa finalité et à la réglementation. Les démonstrations ne déclenchent aucune commande ni réservation réelle.</p>
 <h2>Droit applicable</h2><p>Le site est soumis au droit français, sous réserve des dispositions impératives applicables.</p>
 <h2>Avant publication</h2><p>Cette adaptation des textes de SYSTIA reste à valider avant publication, notamment pour la configuration effective de Vercel, les coordonnées téléphoniques de l’hébergeur et les informations fiscales applicables. Elle ne vaut pas validation juridique.</p>`),
 'confidentialite':page('Politique de confidentialité','PROTECTION DES DONNÉES','Comment vos informations sont utilisées lorsque vous consultez ce site ou préparez une prise de contact.',`
 <h2>1. Responsable du traitement</h2>${identity}
 <h2>2. Données renseignées</h2><p>Le formulaire de contact vous permet de renseigner un prénom ou un nom d’entreprise, une adresse e-mail ou un numéro de téléphone pour vous répondre, le sujet de votre demande et un message. L’outil d’idées utilise les informations que vous indiquez sur votre activité pour générer une proposition personnalisée par IA.</p><p>Le clic sur « Envoyer ma demande » transmet les coordonnées, le sujet et le message au serveur du site, qui les envoie à demande@arnaudcrestey.com via la messagerie Hostinger. Aucune ouverture de votre messagerie personnelle n’est nécessaire. Si vous indiquez une adresse e-mail, un accusé de réception automatique lui est également envoyé ; aucun e-mail de confirmation n’est envoyé lorsque vous indiquez uniquement un téléphone. Les coordonnées du formulaire de contact ne sont pas envoyées à OpenAI. Dans l’atelier, le clic sur « Découvrir mon idée » transmet les réponses au serveur local puis à l’API OpenAI pour générer une proposition. Les champs saisis et le résultat ne sont pas conservés par notre serveur après le traitement ; ils restent dans la page jusqu’à son rechargement. Évitez d’y saisir des données sensibles ou des informations confidentielles sur des tiers.</p><p>Le serveur ne conserve pas de copie du contenu des demandes. Les messages reçus sont conservés dans la boîte de messagerie pour leur traitement.</p>
 <h2>3. Finalités</h2><p>Les informations renseignées permettent de générer une idée adaptée au métier et à l’objectif, d’afficher une démonstration ou de transmettre votre demande de contact. Un message envoyé volontairement depuis le formulaire sert à répondre à votre demande et, le cas échéant, à suivre les échanges professionnels. Aucun profil publicitaire ni statistique de fréquentation n’est produit par cette version.</p>
 <h2>4. Bases légales</h2><p>Lorsqu’un message concerne un projet de prestation, son traitement repose sur les mesures précontractuelles prises à votre demande. Pour une demande générale, il repose sur l’intérêt légitime de l’entreprise à répondre à ses interlocuteurs. Un éventuel traitement nécessitant votre consentement ne sera activé qu’après information et recueil de ce consentement.</p>
 <h2>5. Destinataires et prestataires</h2><p>Les messages effectivement envoyés sont destinés à l’entreprise Arnaud Crestey et aux personnes habilitées à traiter votre demande. Hostinger Email intervient dans l’acheminement des messages et l’hébergement de la boîte destinataire. Les informations ne sont ni vendues ni louées à des tiers à des fins commerciales.</p><p><strong>Vercel Inc. est l’hébergeur retenu pour la future mise en ligne.</strong> Une fois le site publié sur cette plateforme, Vercel pourra traiter les données techniques nécessaires à la diffusion et à la sécurité du site, notamment les adresses IP et les informations de requête. Cet hébergement n’est pas encore actif pour la préversion locale.</p><p>Vercel est établi aux États-Unis et peut traiter des données hors de l’Espace économique européen. Son <a href="https://vercel.com/legal/dpa">accord de traitement des données</a> prévoit des mécanismes d’encadrement des transferts internationaux, dont des clauses contractuelles types selon les situations. Leur application au compte et à la configuration retenue sera vérifiée avant publication. Les modalités contractuelles applicables à la messagerie Hostinger seront vérifiées avant publication. L’atelier utilise l’API OpenAI, un service distant susceptible de traiter les réponses hors de l’Espace économique européen. Seules les réponses au questionnaire et, pour une variante, la question précédemment proposée sont transmises ; aucun compte ni e-mail n’est demandé. La génération est déclenchée par l’utilisateur après information. Les modalités contractuelles, la base légale et les garanties de transfert applicables devront être validées avant publication.</p>
 <h2>6. Durées de conservation</h2><p>Le site ne conserve pas les textes soumis à l’atelier ni les propositions générées sur son serveur. Un compteur technique local conserve uniquement le nombre de tentatives et une estimation du coût, sans les réponses. Les saisies dans le navigateur disparaissent au rechargement. Les appels OpenAI désactivent le stockage des réponses pour récupération ultérieure ; cela n’exclut pas les journaux de surveillance des abus, qui peuvent conserver du contenu jusqu’à 30 jours selon les réglages et exceptions du fournisseur. Les données API ne servent pas à entraîner ses modèles par défaut, sauf partage volontaire. Consultez la <a href="https://developers.openai.com/api/docs/guides/your-data">documentation OpenAI sur les données</a>. Pour le contact, un compteur quotidien limite les envois sans enregistrer leur contenu ; des identifiants techniques temporaires préviennent les doubles envois, pendant au plus 24 heures en mémoire du serveur.</p><p>Pour les messages envoyés, la durée de conservation doit être définie selon le traitement de la demande, le suivi de la relation et les obligations légales éventuelles. Les durées exactes et les règles d’archivage restent à confirmer avant publication ; aucune durée arbitraire n’est présentée ici comme déjà appliquée.</p>
 <h2>7. Sécurité</h2><p>Les démonstrations métiers restent locales. L’atelier IA utilise un serveur intermédiaire : la clé API n’est jamais envoyée au navigateur. La préversion limite la taille des requêtes, leur fréquence et le nombre d’appels ; elle ne journalise pas le contenu des réponses. Pour les messages envoyés, les mesures de sécurité dépendent également des services de messagerie utilisés. Aucune transmission ni aucun stockage numérique ne peut être garanti sans risque.</p>
 <h2>8. Vos droits</h2><p>Selon les conditions prévues par la réglementation, vous pouvez demander l’accès, la rectification, l’effacement ou la limitation de vos données, vous opposer à certains traitements et bénéficier de la portabilité lorsqu’elle s’applique. Si un traitement repose sur votre consentement, vous pouvez le retirer sans remettre en cause sa licéité antérieure.</p><p>Pour exercer vos droits, écrivez à ${email}. Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p>
 <h2>9. Cookies et traceurs</h2><p>La version actuelle n’utilise aucun cookie ni stockage persistant dans le navigateur. Les préférences de lecture ne persistent pas après le rechargement. Consultez la <a href="/cookies/">politique de cookies</a>.</p>
 <h2>10. Sites et services externes</h2><p>Les liens externes et l’ouverture de votre messagerie sont déclenchés à votre initiative. Les services concernés appliquent leurs propres politiques de confidentialité.</p>
 <h2>11. Évolution de cette politique</h2><p>Cette politique décrit la version actuellement testée. Elle sera actualisée et devra être validée avant la mise en ligne et avant tout ajout de formulaire connecté, d’outil IA, de mesure d’audience ou d’autre traitement. Elle ne constitue pas une validation juridique du dispositif futur.</p>`),
 'cookies':page('Politique de cookies','COOKIES ET TRACEURS','Une information précise sur les cookies et les choix disponibles dans la version actuelle du site.',`
 <h2>1. Qu’est-ce qu’un cookie ?</h2><p>Un cookie est un petit fichier déposé sur votre terminal par un site. D’autres technologies peuvent également mémoriser des informations ou suivre la navigation. Leur utilisation dépend de leur finalité et des règles applicables.</p>
 <h2>2. Ce qui est utilisé ici</h2><p>Cette préversion ne dépose aucun cookie et n’utilise ni stockage local persistant, ni mesure d’audience, ni traceur publicitaire. Les images et les polices sont servies avec le site, sans chargement depuis un service externe. Les démonstrations métiers restent dans la mémoire temporaire de la page. L’atelier personnalisé transmet ses réponses à OpenAI lors de la génération, sans déposer de cookie ; ce traitement est décrit dans la politique de confidentialité. Le formulaire de contact envoie votre demande par la messagerie Hostinger, sans déposer de cookie.</p>
 <h2>3. Consentement</h2><p>Aucun bandeau de consentement n’est affiché puisqu’aucun traceur n’est mis en œuvre par cette version. Si des traceurs soumis au consentement sont ajoutés, ils ne seront pas activés avant votre accord. Les finalités, prestataires et durées seront précisés et un moyen de refuser ou de retirer votre accord sera proposé.</p>
 <h2>4. Gestion des préférences</h2><p>Il n’existe actuellement aucun cookie du site à accepter, refuser ou supprimer. Le réglage des animations modifie uniquement l’affichage en cours. Vous pouvez gérer les cookies d’autres sites depuis votre navigateur ; cette page ne modifie pas ces réglages.</p>
 <h2>5. Durée de conservation</h2><p>Aucune durée de conservation de cookie ne s’applique au fonctionnement actuel. Les saisies et préférences temporaires du site disparaissent au rechargement de la page.</p>
 <h2>6. Évolution et contact</h2><p>Vercel est retenu pour l’hébergement lors de la mise en ligne. Ce choix n’active pas à lui seul un outil de mesure d’audience. La configuration effective, les éventuels mécanismes de sécurité et traceurs seront contrôlés avant publication ; cette politique sera adaptée aux seuls outils réellement activés. Les traitements techniques liés à l’hébergement sont distincts du dépôt de cookies et sont décrits dans la <a href="/confidentialite/">politique de confidentialité</a>.</p><p>Pour toute question, contactez ${email}.</p>`)
};
