export const pricingCards = `<div class="pricing-cards pricing-choice-grid">
<article class="price-card"><p class="eyebrow">CLARIFIER VOTRE PROJET</p><h3>Faire le point<br>avant d’agir</h3><p class="price"><strong>190 €</strong></p><p>Comprendre votre situation et choisir les bonnes priorités, sans obligation de commander la suite.</p><ul><li>Votre activité et vos besoins</li><li>Des priorités clarifiées</li><li>Une première direction concrète</li></ul><a class="button button-outline" href="/contact/?sujet=faire-le-point">Faire le point</a></article>
<article class="price-card"><p class="eyebrow">INVITER À PARTICIPER</p><h3>Votre point<br>d’entrée sur mesure</h3><span class="starting">À partir de</span><p class="price"><strong>490 €</strong></p><p>Une première interaction utile, pensée pour votre métier et les clients à qui vous vous adressez.</p><ul><li>Faire le point inclus</li><li><span class="pricing-phrase">Un vote, un choix</span> <span class="pricing-phrase">ou un parcours adapté</span></li><li>La conception du point d’entrée</li></ul><a class="button button-outline" href="/contact/?sujet=point-entree">Créer mon point d’entrée</a></article>
<article class="price-card"><p class="eyebrow">PRÉSENTER VOTRE ACTIVITÉ</p><h3>Votre site<br>vitrine</h3><span class="starting">À partir de</span><p class="price"><strong>990 €</strong></p><p>Un site pour présenter votre métier, vos prestations et faciliter la prise de contact.</p><ul><li>Faire le point inclus</li><li>Un site à l’image de votre activité</li><li><span class="pricing-phrase">Adapté aux ordinateurs,</span> <span class="pricing-phrase">tablettes et téléphones</span></li></ul><a class="button button-outline" href="/contact/?sujet=site-vitrine">Créer mon site vitrine</a></article>
<article class="price-card featured"><p class="eyebrow">CONCEVOIR L’ENSEMBLE</p><h3>Votre système<br>complet</h3><span class="starting">À partir de</span><p class="price"><strong>1 390 €</strong></p><p>Votre site et son premier point d’entrée, pensés ensemble pour votre activité.</p><ul><li>Faire le point inclus</li><li>Un site à l’image de votre activité</li><li><span class="pricing-phrase">Adapté aux ordinateurs,</span> <span class="pricing-phrase">tablettes et téléphones</span></li><li>Un premier point d’entrée intégré</li></ul><a class="button button-gold" href="/contact/?sujet=systeme-complet">Parlons de mon projet</a></article>
</div><p class="micro-note pricing-vat">TVA non applicable, art. L. 223-3 du CIBS. Les prix affichés sont les montants à payer.</p>`;

export const pricingPage = `<section class="page-intro section"><p class="eyebrow">FORMATS &amp; TARIFS</p><h1>Le bon point de départ.<br><em>La suite, à votre rythme.</em></h1><p>Un site, un point d’entrée ou les deux.<br>Choisissez selon votre besoin, puis faites évoluer votre projet.</p></section>
<section class="section pricing-full">${pricingCards}
<section class="payment-section payment-simple" aria-labelledby="payment-title"><div><p class="eyebrow">LE PAIEMENT DE LA CRÉATION</p><h2 id="payment-title">Votre création,<br><em>réglée en deux fois.</em></h2><p>Le montant de votre projet est fixé au devis.</p></div><div class="payment-options"><article><h3>Au démarrage du projet</h3><p><strong>30 %</strong><span>D’ACOMPTE</span></p></article><article><h3>À la mise en ligne</h3><p><strong>70 %</strong><span>APRÈS VOTRE VALIDATION</span></p></article></div></section>
<section class="followup-section" id="suivi"><p class="eyebrow">APRÈS LA MISE EN LIGNE</p><h2>Faire vivre <em>votre site.</em></h2><p>Un abonnement pour le fonctionnement. Des évolutions quand vous en avez besoin.</p><div class="followup-grid"><article><span class="eyebrow">LE SUIVI MENSUEL</span><p class="price"><strong>29 €</strong><span>PAR MOIS</span></p><ul><li>Hébergement du site</li><li>Entretien technique</li><li>Assistance par e-mail liée au fonctionnement du site</li></ul><p class="micro-note">À partir de la mise en ligne. Sans engagement de durée, avec un mois de préavis. Les modifications de contenu, les évolutions et les nouvelles fonctionnalités sont facturées séparément.</p></article><article><span class="eyebrow">UNE NOUVEAUTÉ À PARTAGER ?</span><p class="starting">À partir de</p><p class="price"><strong>39 €</strong><span>PAR INTERVENTION</span></p><ul><li>Annoncer une offre ou un événement</li><li>Présenter un produit de saison</li><li>Actualiser un texte, une photo ou vos horaires</li><li>Modifier un contenu ou un choix dans votre point d’entrée</li></ul><p class="micro-note">Tarif confirmé selon votre demande avant toute intervention ; textes et photos fournis par vos soins. Un renouvellement complet ou une nouvelle mécanique fait l’objet d’un devis spécifique.</p></article></div><p class="micro-note">Le suivi et les interventions sont distincts du prix de création, y compris pour le système complet.</p></section>
</section>`;
