const projects=[
 {id:'osys',name:'OSYS',sector:'PRÉVENTION & ORIENTATION',line:'Des repères, quand ils comptent.',description:'Un univers sobre pour aborder la prévention, préparer les informations utiles et trouver des repères. Une entrée claire pour un sujet qui demande de l’attention.',url:'https://www.osys14.com/',effect:'depth'},
 {id:'qlyk',name:'Qlyk Studio Auto',sector:'IMAGE & AUTOMOBILE',line:'Un autre regard sur le véhicule.',description:'Une présentation premium pour un studio qui valorise l’environnement visuel des véhicules, sans modifier le véhicule lui-même. Un univers affirmé, au service de l’image.',url:'https://www.qlykstudio.fr/',effect:'light'},
 {id:'czame',name:'C·zame',sector:'DIALOGUE & PRÉVENTION',line:'Trouver les mots pour ouvrir le dialogue.',description:'Une porte d’entrée pour clarifier une situation sensible liée à une conduite addictive et préparer une conversation.',url:'https://www.czame.fr/',effect:'reveal'}
];
const articles=projects.map((project,index)=>`<article class="realisation-story realisation-story--${project.effect}" aria-labelledby="realisation-${project.id}">
 <a class="realisation-visual" href="${project.url}" target="_blank" rel="noopener noreferrer" aria-label="Découvrir ${project.name}, ouvrir le site dans un nouvel onglet"><span class="realisation-window"><span></span><span></span><span></span><span class="realisation-domain">${new URL(project.url).hostname.replace(/^www\./,'')}</span></span><img src="/assets/realisation-${project.id}.jpg" alt="Aperçu de la page d’accueil de ${project.name}" width="1440" height="1000" loading="${index?'lazy':'eager'}" decoding="async"><span class="realisation-visit">Explorer le site <span aria-hidden="true">↗</span></span></a>
 <div class="realisation-copy"><p class="eyebrow">${project.sector}</p><h2 id="realisation-${project.id}">${project.name}</h2><p class="realisation-line">${project.line}</p><p class="realisation-description">${project.description}</p><a class="under-link" href="${project.url}" target="_blank" rel="noopener noreferrer" aria-label="Découvrir ${project.name}, ouvrir le site dans un nouvel onglet">Découvrir le site <span aria-hidden="true">↗</span></a></div>
</article>`).join('');
export const realisationPages={realisations:{title:'Réalisations — Arnaud Crestey',description:'OSYS, Qlyk Studio Auto, C·zame : découvrez des sites créés par Arnaud Crestey, leurs univers et leurs points d’entrée.',content:`<section class="realisations-intro section"><p class="eyebrow">RÉALISATIONS</p><h1>Des idées qui deviennent<br><em>des sites.</em></h1><p>Des projets différents. Une même attention : donner à chaque univers une présence claire, vivante et singulière.</p><a href="#les-realisations" class="realisations-scroll" aria-label="Découvrir les réalisations"><span>Explorer</span><span aria-hidden="true">↓</span></a></section><section class="realisations-magazine section" id="les-realisations" aria-label="Les réalisations d’Arnaud Crestey">${articles}</section><section class="realisations-next section"><p class="eyebrow">ET POUR VOTRE ACTIVITÉ ?</p><h2>Votre projet a aussi<br><em>son univers.</em></h2><a class="button button-dark" href="/contact/">Parlons de votre activité <span aria-hidden="true">↗</span></a></section>`}};
