const projects=[
 {id:'osys',name:'OSYS',sector:'PRÉVENTION & ORIENTATION',line:'Des repères, quand ils comptent.',description:'Un univers sobre pour aborder la prévention, préparer les informations utiles et trouver des repères. Une entrée claire pour un sujet qui demande de l’attention : les violences conjugales.',url:'https://www.osys14.com/',effect:'depth'},
 {id:'qlyk',name:'Qlyk Studio Auto',sector:'IMAGE & AUTOMOBILE',line:'Un autre regard sur le véhicule.',description:'Une présentation premium pour un studio qui valorise l’environnement visuel des véhicules, sans modifier le véhicule lui-même. Un univers affirmé, au service de l’image.',url:'https://www.qlykstudio.fr/',effect:'light'},
 {id:'czame',name:'C·zame',sector:'DIALOGUE & PRÉVENTION',line:'Trouver les mots pour ouvrir le dialogue.',description:'Une porte d’entrée pour clarifier une situation sensible liée à une conduite addictive et préparer une conversation.',url:'https://www.czame.fr/',effect:'reveal'},
 {id:'normandine',name:'La Normandine',sector:'IMMOBILIER & LIEU DE VIE',line:'Découvrir un lieu avant de le visiter.',description:'Une vitrine pour découvrir une propriété de caractère en Normandie, ses deux maisons et ses espaces.',url:'https://normandine.arnaudcrestey.com/',effect:'depth'},
 {id:'arhi',name:'ARHI',sector:'COMPATIBILITÉS PROFESSIONNELLES',line:'Mieux comprendre une collaboration.',description:'Une présentation claire d’un outil consacré aux compatibilités professionnelles, pour explorer les dynamiques humaines et les points de vigilance d’une collaboration.',url:'https://arhi.fr/',effect:'light'},
 {id:'langochat',name:'LANGOCHAT',sector:'COMPRÉHENSION & DIALOGUE',line:'Comprendre avant de répondre.',description:'Un espace pour aider les adultes à trouver les mots justes, comprendre une situation et préparer le dialogue.',url:'https://www.langochat.fr/',effect:'reveal'}
];
const entryPoints=[
 {id:'expertise',name:'AC Expertise',sector:'CONSULTANTS, FORMATEURS & INDÉPENDANTS',description:'Cinq questions pour faire le point sur la clarté de votre offre et la façon dont votre communication donne envie de faire appel à vous.',url:'https://expertise.arnaudcrestey.com/'},
 {id:'premierpas',name:'AC Accompagnement',sector:'BIEN-ÊTRE & ACCOMPAGNEMENT',description:'Cinq questions pour regarder votre communication avec les yeux d’une personne qui découvre votre activité et hésite à vous contacter.',url:'https://premierpas.arnaudcrestey.com/'},
 {id:'immobilier',name:'AC Immobilier',sector:'PROFESSIONNELS DE L’IMMOBILIER',description:'Cinq questions pour réfléchir à la confiance que votre communication inspire à une personne qui envisage de vous confier un bien.',url:'https://immobilier.arnaudcrestey.com/'}
];
const entryCards=entryPoints.map(point=>`<article class="entrypoint-card" aria-labelledby="entrypoint-${point.id}">
 <a class="entrypoint-visual" href="${point.url}" target="_blank" rel="noopener noreferrer" aria-label="Découvrir ${point.name}, ouvrir le parcours dans un nouvel onglet"><span class="realisation-window"><span></span><span></span><span></span><span class="realisation-domain">${new URL(point.url).hostname}</span></span><img src="/assets/realisation-${point.id}.jpg" alt="Aperçu du point d’entrée ${point.name}" width="1440" height="1000" loading="lazy" decoding="async"></a>
 <div class="entrypoint-copy"><p class="eyebrow">${point.sector}</p><h3 id="entrypoint-${point.id}">${point.name}</h3><p>${point.description}</p><a class="under-link" href="${point.url}" target="_blank" rel="noopener noreferrer" aria-label="Découvrir ${point.name}, ouvrir le parcours dans un nouvel onglet">Découvrir le parcours <span aria-hidden="true">↗</span></a></div>
</article>`).join('');
const articles=projects.map((project,index)=>`<article class="realisation-story realisation-story--${project.effect}" aria-labelledby="realisation-${project.id}">
 <a class="realisation-visual" href="${project.url}" target="_blank" rel="noopener noreferrer" aria-label="Découvrir ${project.name}, ouvrir le site dans un nouvel onglet"><span class="realisation-window"><span></span><span></span><span></span><span class="realisation-domain">${new URL(project.url).hostname.replace(/^www\./,'')}</span></span><img src="/assets/realisation-${project.id}.jpg" alt="Aperçu de la page d’accueil de ${project.name}" width="1440" height="1000" loading="${index?'lazy':'eager'}" decoding="async"><span class="realisation-visit">Explorer le site <span aria-hidden="true">↗</span></span></a>
 <div class="realisation-copy"><p class="eyebrow">${project.sector}</p><h2 id="realisation-${project.id}">${project.name}</h2><p class="realisation-line">${project.line}</p><p class="realisation-description">${project.description}</p><a class="under-link" href="${project.url}" target="_blank" rel="noopener noreferrer" aria-label="Découvrir ${project.name}, ouvrir le site dans un nouvel onglet">Découvrir le site <span aria-hidden="true">↗</span></a></div>
</article>`).join('');
export const realisationPages={realisations:{title:'Réalisations — Arnaud Crestey',description:'Six sites et trois points d’entrée interactifs : découvrez les réalisations d’Arnaud Crestey.',content:`<section class="realisations-intro section"><p class="eyebrow">RÉALISATIONS</p><h1>Des idées qui deviennent<br><em>des sites.</em></h1><p>Des projets différents. Une même attention : donner à chaque univers une présence claire, vivante et singulière.</p><nav class="realisations-categories" aria-label="Les deux rubriques des réalisations"><a href="#les-realisations">Les sites <span aria-hidden="true">↓</span></a><a href="#les-points-entree">Les points d’entrée <span aria-hidden="true">↓</span></a></nav></section><section class="realisations-sites" id="les-realisations" aria-labelledby="realisations-sites-title"><div class="realisations-section-heading section"><p class="eyebrow">LES SITES</p><h2 id="realisations-sites-title">Une activité, un univers,<br><em>un site pour les découvrir.</em></h2></div><div class="realisations-magazine section">${articles}</div></section><section class="realisations-entrypoints section" id="les-points-entree" aria-labelledby="realisations-entrypoints-title"><div class="entrypoints-heading"><p class="eyebrow">LES POINTS D’ENTRÉE</p><h2 id="realisations-entrypoints-title">Des parcours interactifs<br><em>pour ouvrir le dialogue.</em></h2><p>Vos visiteurs répondent à quelques questions en lien avec votre activité. Un moyen simple de les aider à préciser leur besoin et de préparer un premier échange avec vous.</p></div><div class="entrypoints-grid">${entryCards}</div></section><section class="realisations-next section"><p class="eyebrow">ET POUR VOTRE ACTIVITÉ ?</p><h2>Votre projet a aussi<br><em>son univers.</em></h2><a class="button button-dark" href="/contact/">Parlons de votre activité <span aria-hidden="true">↗</span></a></section>`}};
